import type { Article } from './types';

// Source links were read on 2026-10-04. Answers are original caregiver guidance,
// not diagnostic rules; retain IDs when revising a question's wording.
const cp = (title: string, path: string) => ({ title: `Cats Protection · ${title}`, url: `https://www.cats.org.uk/${path}` });
const cornell = (title: string, slug: string) => ({ title: `Cornell Feline Health Center · ${title}`, url: `https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/${slug}` });
const references = {
  sleep: cp('Cats and sleep', 'help-and-advice/cat-behaviour/cats-and-sleep'),
  dawn: { title: 'Cats Protection LearnOnline · Hunters: domestic cat', url: 'https://learnonline.cats.org.uk/content/ufo/8.html' },
  night: cp('Cats at night', 'help-and-advice/home-and-environment/cats-at-night'),
  body: cp('Cat body language', 'help-and-advice/cat-behaviour/cat-body-language'),
  purr: cp('Why does my cat purr?', 'cats-blog/why-does-my-cat-purr'),
  meow: cp('What does my cat’s miaow mean?', 'cats-blog/what-does-my-cats-miaow-mean'),
  tail: cp('Cat tail meanings', 'cats-blog/why-do-cats-have-tails'),
  belly: cp('Why cats show their tummies', 'cats-blog/why-cats-show-their-tummies'),
  aggression: cp('Aggressive cats', 'help-and-advice/cat-behaviour/aggressive-cats'),
  feeding: cp('Feeding your cat', 'help-and-advice/diet/feeding'),
  drinking: cp('Cats and drinking', 'help-and-advice/diet/cats-and-drinking'),
  water: cp('8 tips to get your cat to drink more water', 'cats-blog/8-tips-get-your-cat-to-drink-more-water'),
  litter: cp('Cats and toileting', 'help-and-advice/cat-behaviour/toileting'),
  substrate: { title: 'Cats Protection LearnOnline · Toileting: domestic cat', url: 'https://learnonline.cats.org.uk/content/ufo/20.html' },
  spraying: cp('Cats and spraying', 'help-and-advice/cat-behaviour/spraying'),
  play: cp('Cats and play', 'help-and-advice/cat-behaviour/cats-and-play'),
  scratch: cp('Cats and scratching', 'help-and-advice/cat-behaviour/scratching'),
  safe: cp('Keeping your cat safe in the home', 'help-and-advice/getting-a-cat/keeping-your-cat-safe'),
  groom: cp('Grooming your cat', 'help-and-advice/cat-behaviour/grooming'),
  bath: cp('Should I bathe my cat?', 'cats-blog/should-i-bathe-my-cat'),
  longhair: cp('Tips for grooming long-haired cats', 'cats-blog/tips-for-grooming-long-haired-cats'),
  claws: cp('How to trim cat claws', 'help-and-advice/health/how-to-trim-cat-claws'),
  skin: cp('Skin problems in cats', 'help-and-advice/health/skin-problems-in-cats'),
  boxes: cp('Why do cats love boxes?', 'cats-blog/why-do-cats-love-boxes'),
  hiding: cp('Cats hiding', 'help-and-advice/cat-behaviour/cats-hiding'),
  newhome: cp('Bringing a cat home', 'help-and-advice/home-and-environment/bringing-a-cat-home'),
  moving: cp('Moving house with a cat', 'help-and-advice/home-and-environment/moving-home-with-your-cat'),
  indoor: cp('Indoor cats', 'help-and-advice/home-and-environment/indoor-cats'),
  shy: cp('Shy cats', 'help-and-advice/cat-behaviour/shy-cats'),
  stress: cp('Spotting signs of cat stress', 'help-and-advice/health/cat-stress'),
  knead: cp('Why do cats knead?', 'cats-blog/why-do-cats-knead'),
  blink: cp('Why do cats slow blink?', 'cats-blog/why-do-cats-slow-blink'),
  bite: cp('Why does my cat bite me?', 'cats-blog/why-does-my-cat-bite-me'),
  introduce: cp('Introducing cats and kittens', 'help-and-advice/cat-behaviour/introducing-cats'),
  fighting: cp('Cats and fighting', 'help-and-advice/cat-behaviour/cats-and-fighting'),
  pain: cp('Signs of pain', 'help-and-advice/health/signs-of-pain'),
  elderly: cp('Elderly cats: care guide', 'help-and-advice/health/elderly-cats'),
  senior: cornell('The special needs of the senior cat', 'special-needs-senior-cat'),
  nutrition: cornell('Feeding your cat', 'feeding-your-cat'),
  obesity: cornell('Obesity', 'obesity'),
  appetite: cornell('Anorexia', 'anorexia'),
  urinary: cornell('Feline lower urinary tract disease', 'feline-lower-urinary-tract-disease'),
  soiling: cornell('House soiling', 'feline-behavior-problems-house-soiling'),
  licking: cornell('Cats that lick too much', 'cats-lick-too-much'),
  cornellAggression: cornell('Aggression', 'feline-behavior-problems-aggression'),
  meal: { title: 'FelineVMA · How to feed a cat', url: 'https://catfriendly.com/wp-content/uploads/2025/02/FelineVMAHowtoFeedCat_Web.pdf' },
  environment: { title: 'AAFP / ISFM · Your cat’s environmental needs', url: 'https://catfriendly.com/wp-content/uploads/2022/05/AAFPEnvironmentalGuidelinesBrochure.pdf' },
  pillars: { title: 'AAFP / ISFM · Feline environmental needs guidelines', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11383066/' },
  indoorNeeds: { title: 'FelineVMA · Physical and emotional needs of indoor cats (2025)', url: 'https://catvets.com/resource/2025-meeting-the-physical-and-emotional-needs-of-indoor-cats/' },
  tension: { title: 'FelineVMA · Intercat tension guidelines (2024)', url: 'https://catvets.com/resource/2024-intercat-tension-guidelines/' },
  carrier: { title: 'FelineVMA · Turn your cat carrier into a home away from home', url: 'https://catfriendly.com/wp-content/uploads/2021/08/Carrier-Home.pdf' },
  training: { title: 'FelineVMA · Cat training techniques for caregivers', url: 'https://catfriendly.com/wp-content/uploads/2025/12/FelineVMA_Cat_Training_Techniques_for_Caregivers_Handout.pdf' },
  chronicPain: { title: 'AAFP / ISFM · Signs of chronic pain and changes in the home', url: 'https://catfriendly.com/wp-content/uploads/2024/04/AAFP_Client_Broch_Guideline_Chronic_Pain_with_NSAIDs.pdf' },
  inappetence: { title: 'International Cat Care · Managing the cat that won’t eat', url: 'https://icatcare.org/resources/cat-carer-guide-managing-the-cat-that-wont-eat.pdf' },
  urinaryGuide: { title: 'International Cat Care · Cat carer guide to lower urinary tract diseases', url: 'https://icatcare.org/resources/cat-carer-guide-urinary-tract-diseases.pdf' },
  kitten: { title: 'International Cat Care · Caring for your new kitten (2024)', url: 'https://icatcare.org/resources/icatcare-kitten-booklet-2024.pdf' },
  digestive: cp('Digestive disorders (2025)', 'media/pmilawnv/digestive-disorders-2025.pdf'),
  vcaPain: { title: 'VCA Animal Hospitals · Signs of pain in cats', url: 'https://vcahospitals.com/alexandria/know-your-pet/how-do-i-know-if-my-cat-is-in-pain' },
  laser: { title: 'Kogan & Grigg (2021) · Laser play and guardian-reported repetitive behaviors', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8388446/' },
  foreignBodies: { title: 'American College of Veterinary Surgeons · Gastrointestinal foreign bodies', url: 'https://www.acvs.org/small-animal/gastrointestinal-foreign-bodies/' },
  swallowedString: { title: 'Animal Trust Vets · Foreign-body bowel obstruction in dogs and cats', url: 'https://www.animaltrust.org.uk/pet-health-advice-hub/bowel-obstruction-in-dogs-and-cats' },
  toxicHazards: { title: 'VCA Animal Hospitals · Toxic household hazards for cats', url: 'https://vcahospitals.com/greater-savannah/know-your-pet/household-hazards-toxic-hazards-for-cats' },
};

const article = (id: string, category: Article['category'], zh: Article['answer']['zh-CN'], en: Article['answer']['en'], sources: Article['sources'], urgent = false): Article => ({
  id, category, answer: { 'zh-CN': zh, en }, sources, reviewedAt: '2026-10-04', ...(urgent ? { urgent: true } : {}),
});

export const articles: Article[] = [
  article('cat-sleep-duration', 'sleep', {
    question: '猫为什么一天睡那么久？',
    shortAnswer: '长时间、分段地休息是猫的常见作息。判断是否正常，更有用的是看它醒来后的精神、进食和活动，以及与自己平常相比有没有变化。',
    reasons: '猫保留了短时间追逐、捕猎后休息的行为节奏，白天也会交替打盹和清醒。幼猫成长需要休息，老年猫的体力与行动能力可能改变；同龄猫之间也有差异。闭着眼安静趴着并不总是深睡，不能只凭一张睡觉照片判断健康，也不必拿固定小时数要求每只猫。',
    actions: ['安排安静、舒适且不会被频繁打扰的休息区，让猫自己选择位置。', '在它自然醒来、愿意互动时提供短游戏和探索机会，不为调整作息强行叫醒。', '留意几天里的日常节奏，并把食欲、排泄和玩耍一起记录，建立属于这只猫的基线。'],
    keywords: ['睡觉', '睡眠时间', '打盹', '作息'],
  }, {
    question: 'Why does my cat sleep so much?',
    shortAnswer: 'Long periods of rest, broken into several naps, are common in cats. Compare your cat with their usual routine and consider how they eat, move and behave when awake.',
    reasons: 'Cats retain a pattern of resting between brief bouts of hunting or chasing. Dozing alternates with alert periods. Growing kittens need rest, while older cats may have different stamina and mobility; individuals also differ. A cat lying still with closed eyes is not necessarily deeply asleep. A photograph or a fixed daily sleep target cannot establish whether a cat is healthy.',
    actions: ['Offer comfortable resting places where people will not repeatedly interrupt them, and let them choose.', 'Offer short games and exploration when they wake naturally and want to participate; do not keep them awake to change their schedule.', 'Record daily patterns alongside appetite, toileting and play to learn this cat’s normal baseline.'],
    keywords: ['sleep', 'naps', 'sleeping hours', 'routine'],
  }, [references.sleep]),
  article('cat-dawn-dusk', 'sleep', {
    question: '猫为什么清晨或傍晚特别活跃？',
    shortAnswer: '不少猫在晨昏时段更愿意探索和玩耍，这是常见的活动节奏。家猫也会受家庭生活影响，并不是每只都严格遵循同一张时间表。',
    reasons: '晨昏活动与祖先捕猎小型猎物的机会有关，吃饱也不代表捕猎式游戏的需求消失。幼猫和年轻猫往往精力更充足，窗外鸟声、光线和人的起床动作也可能成为活动提示。白天一直缺少互动的猫，到了家人回家时更可能集中释放精力；这些情况需要结合环境理解。',
    actions: ['观察它最愿意玩的时段，在清晨或傍晚安排几次短互动，把追逐引向逗猫棒。', '提供安全的观察点、抓板和可探索空间，满足醒着时的活动需求。', '保持大致稳定的进食与互动节奏，游戏结束后给它放松机会，不要求立即入睡。'],
    keywords: ['清晨', '傍晚', '晨昏', '活跃'],
  }, {
    question: 'Why is my cat more active at dawn and dusk?',
    shortAnswer: 'Many cats are keen to explore or play around dawn and dusk. This is a common rhythm, although household routines influence activity and individual cats do not follow an identical timetable.',
    reasons: 'Activity at these times relates to hunting opportunities in their ancestors. Being well fed does not remove the drive for hunting-style play. Kittens and young cats often have more energy. Bird sounds, changing light and people getting up can also prompt activity. A cat with little stimulation during the day may concentrate play when the family returns; interpret the pattern in its setting.',
    actions: ['Notice their preferred play periods and offer several short morning or evening games with a wand toy.', 'Provide safe observation spots, scratching surfaces and places to explore when awake.', 'Keep feeding and interaction reasonably predictable, then allow time to settle after play without demanding immediate sleep.'],
    keywords: ['dawn', 'dusk', 'crepuscular', 'active'],
  }, [references.dawn]),
  article('cat-night-activity', 'sleep', {
    question: '猫半夜跑酷、叫醒主人怎么办？',
    shortAnswer: '先分清这是平常的玩耍、讨食，还是新出现的焦躁或不适。通过白天和傍晚的活动、稳定喂食与安全环境，可以逐步改善夜间打扰。',
    reasons: '猫的活动时间不一定和人一致，年轻猫尤其容易精力旺盛。有些猫发现叫声能换来立即喂食或互动，会反复使用这个办法；另一些可能受到窗外动物、噪声或资源不方便使用的影响。老年猫新出现夜叫、迷路样徘徊，不能直接解释成故意捣乱。',
    actions: ['白天和早晚分散安排短游戏，给睡前留出安静放松时间，不用强行剥夺白天睡眠。', '确认夜间能方便使用水、猫砂盆和睡窝；确有讨食需求时，把日粮分配到定时喂食器。', '满足基本需求后保持夜间回应一致，把主动陪玩安排到固定时段，避免每次叫醒都加餐。'],
    watch: '若夜间活动突然改变，伴随持续叫喊、方向感变化或其他异常，联系兽医排查健康原因。',
    keywords: ['半夜', '跑酷', '夜叫', '叫醒'],
  }, {
    question: 'What can I do about night-time zoomies and wake-ups?',
    shortAnswer: 'Distinguish usual play or requests for food from new restlessness or discomfort. Daytime and early-evening activity, predictable feeding and accessible resources can gradually reduce disruption.',
    reasons: 'A cat’s active hours may differ from yours, especially when young. Some learn that calling brings immediate food or attention. Others respond to animals outside, noise or difficulty accessing resources. New night-time calling or confused wandering in an older cat should not be dismissed as deliberate mischief.',
    actions: ['Spread short play sessions across the day and early evening, allowing quiet settling time before bed; do not deprive them of daytime sleep.', 'Ensure water, litter boxes and beds are accessible overnight. For genuine food requests, allocate part of the daily ration to a timed feeder.', 'Once needs are met, respond consistently at night and schedule play predictably instead of adding food at every wake-up.'],
    watch: 'Contact a veterinarian for a sudden change, persistent calling, disorientation or other unusual signs.',
    keywords: ['night', 'zoomies', 'waking', 'calling'],
  }, [references.night, references.senior]),
  article('cat-sleeping-spots', 'sleep', {
    question: '猫为什么喜欢暖和、狭小或高处的睡觉位置？',
    shortAnswer: '这些位置可能同时提供温暖、遮挡和观察环境的机会。重点是让猫能安全进出、有其他选择，而不是把它固定在主人认为最舒服的位置。',
    reasons: '有边界的空间能减少背后被突然接近的感觉，高处有助于观察周围；柔软、熟悉气味的垫子也可能更受欢迎。不过不同猫偏好不同，天气、家人活动和同住动物都会改变选择。狭小不等于任何缝隙都安全，热源旁也可能过热；老年猫可能喜欢高处却已不方便跳跃。',
    actions: ['提供几种开放或半遮挡的睡窝，放在安静处，允许猫自主更换。', '固定高处平台并安排稳定台阶，避免跌落、卡住和只有一个容易被堵住的出口。', '避开烫热表面和危险夹缝，关闭洗衣机等设备前检查；保留常温休息区，让猫能够离开热源。'],
    keywords: ['睡窝', '高处', '暖和', '狭小'],
  }, {
    question: 'Why does my cat sleep in warm, enclosed or elevated spots?',
    shortAnswer: 'These places can offer warmth, shelter and a view of the surroundings. Safe access and a choice of resting areas matter more than making a cat use the bed you chose.',
    reasons: 'Sheltered sides may reduce unexpected approaches, while height provides a lookout. Soft bedding and familiar smells may add appeal. Preferences vary with weather, household activity and other animals. Small spaces are not automatically safe, and heat sources may become too hot. Older cats may still prefer height while finding jumping difficult.',
    actions: ['Offer open and partly sheltered beds in quiet locations and let the cat move between them.', 'Secure elevated platforms and provide stable steps; avoid falls, trapping gaps and a single exit another pet can block.', 'Avoid hot surfaces and dangerous gaps, check appliances before closing them, and offer an unheated resting area so the cat can leave warmth.'],
    keywords: ['bed', 'warmth', 'height', 'enclosed'],
  }, [references.environment, references.safe]),
  article('cat-sleep-change', 'sleep', {
    question: '猫突然睡得更多、活动减少，该留意什么？',
    shortAnswer: '与自己平常相比突然变懒、躲藏或不愿活动，值得联系兽医。不能因为猫本来爱睡，或已经年老，就把明显变化当作正常。',
    reasons: '活动减少可能与疼痛、行动困难或其他疾病有关，也可能受到环境变化影响，单凭睡眠无法确定原因。幼猫和老年猫确实有不同的休息需求，但年龄不能解释所有新变化。有些疼痛表现很细微，例如不再跳上常去的窗台、梳毛减少，或被碰到时退缩，而不是明显跛行。',
    actions: ['记录变化开始时间、食欲、饮水、排泄和跳跃表现，拍下自然活动的视频供兽医参考。', '安排健康检查，同时把水、食物和低入口猫砂盆放到容易到达的位置。', '保持安静和舒适，不强迫运动，也不自行用人的止痛药测试是不是疼痛。'],
    watch: '若难以唤醒、站立困难或呼吸异常，应立即联系急诊兽医；停止进食也要尽快咨询。',
    keywords: ['嗜睡', '活动减少', '老年猫', '疼痛'],
  }, {
    question: 'What should I notice if my cat suddenly sleeps more and moves less?',
    shortAnswer: 'A sudden reduction in activity, withdrawal or reluctance to move warrants veterinary advice. A cat’s tendency to sleep, or advanced age, does not explain away a marked new change.',
    reasons: 'Pain, impaired mobility, other illnesses or environmental changes may reduce activity. Sleep alone cannot identify the cause. Kittens and seniors have different resting needs, but age cannot explain every new sign. Pain can appear subtly: avoiding a favorite windowsill, grooming less or withdrawing from touch rather than visibly limping.',
    actions: ['Note when the change started and track appetite, drinking, toileting and jumping; film natural movements for your veterinarian.', 'Arrange a health assessment and make food, water and a low-entry litter box easy to reach.', 'Provide quiet comfort without forced exercise or experimenting with human pain medicines.'],
    watch: 'Difficulty waking, difficulty standing or abnormal breathing requires immediate emergency veterinary advice. Stopping eating also needs prompt advice.',
    keywords: ['lethargy', 'less active', 'senior', 'pain'],
  }, [references.chronicPain, references.pain, references.senior]),
  article('cat-purring', 'communication', {
    question: '猫呼噜就一定开心吗？',
    shortAnswer: '不一定。呼噜常出现在放松的互动中，也可能出现在紧张或疼痛时；要把声音、全身姿态和当时情境放在一起看。',
    reasons: '同一种声音可以服务于不同情境，音量大小也不能直接量出快乐程度。主动靠近、身体松弛和愿意留下，通常比单独听呼噜更能说明互动是否舒服。在医院或受伤时仍呼噜，并不能据此排除不适。并非每只猫都明显呼噜，不呼噜也不代表不亲近或没有感情。',
    actions: ['先观察耳朵、身体是否紧绷，以及猫能否自由离开，再决定是否继续抚摸。', '用短而轻的互动回应，停一下看它是否主动靠近；退缩或甩尾时就结束。', '留意呼噜是否出现在反常情境，并记录同一时段的食欲、活动和躲藏变化。'],
    watch: '呼噜伴随新出现的行动困难、食欲下降或蜷缩紧绷，联系兽医，不用呼噜声当作健康保证。',
    keywords: ['呼噜', '咕噜', '开心', '身体语言'],
  }, {
    question: 'Does purring always mean my cat is happy?',
    shortAnswer: 'No. Purring often accompanies relaxed interaction, but it can also occur during stress or pain. Read the sound together with posture and context.',
    reasons: 'The same sound can occur in different situations, and volume is not a happiness scale. Voluntary approach, a loose body and choosing to stay are usually more informative than purring alone. Purring at a clinic or after injury does not rule out discomfort. Some cats barely purr audibly; that does not mean they lack a bond or affection.',
    actions: ['Check ears, body tension and whether the cat can leave before continuing to pet.', 'Keep contact brief and gentle, then pause to see whether they approach again; end it if they withdraw or lash their tail.', 'Notice purring in unusual situations and record accompanying changes in appetite, movement or hiding.'],
    watch: 'Seek veterinary advice if purring accompanies new mobility problems, reduced appetite or a tense, hunched posture; it is not proof of good health.',
    keywords: ['purr', 'happy', 'body language', 'comfort'],
  }, [references.purr, references.vcaPain]),
  article('cat-meowing', 'communication', {
    question: '猫一直喵喵叫，可能在表达什么？',
    shortAnswer: '可能是寻求互动、食物或通行机会，也可能是紧张、不舒服。没有一套适用于所有猫的叫声翻译，观察发生的时间与前后行为更有帮助。',
    reasons: '猫会在与人相处中学会使用叫声，性格和个体经历使叫声频率差异很大。站在食盆旁叫和在猫砂盆里叫，需要不同的回应；每次叫就立即给零食也可能让讨食持续。老年猫突然频繁叫、夜间徘徊，可能涉及健康或认知变化，需要检查而不是一律忽略。',
    actions: ['先检查水、食物安排、猫砂盆与门是否可用，并排除被关住等实际问题。', '记录何时叫、叫之前发生什么、回应后怎样变化，安排可预测的陪玩与喂食。', '基本需求得到满足后，奖励安静、主动靠近等合适互动，不靠吼叫或惩罚压住声音。'],
    watch: '突然变得爱叫，或伴随食欲、排泄、方向感变化，应咨询兽医；排尿用力却少尿或无尿立即就医。',
    keywords: ['喵喵', '叫声', '夜叫', '沟通'],
  }, {
    question: 'What might constant meowing mean?',
    shortAnswer: 'A cat may want interaction, food or access, or may feel distressed or uncomfortable. There is no universal meow dictionary; timing and surrounding behavior are more useful.',
    reasons: 'Cats learn to use calls with people, and personality and experience shape how vocal each one is. Calling at a bowl and calling while toileting require different responses. Treats after every meow may sustain requests. New frequent calling or night-time wandering in an older cat can involve medical or cognitive changes and deserves assessment rather than blanket ignoring.',
    actions: ['Check access to water, scheduled food, litter boxes and doors, including whether the cat is trapped somewhere.', 'Record the setting and your response, and offer predictable feeding and play.', 'Once needs are met, reward quiet approaches and appropriate interaction rather than shouting or punishing.'],
    watch: 'Consult a veterinarian for a sudden vocal change or appetite, toileting or orientation changes. Straining with little or no urine needs immediate care.',
    keywords: ['meow', 'vocal', 'calling', 'communication'],
  }, [references.meow, references.senior, references.urinary]),
  article('cat-tail-signals', 'communication', {
    question: '尾巴竖起、甩动或夹紧分别怎么看？',
    shortAnswer: '竖尾常见于友好靠近，明显甩尾可能提示兴奋或不耐，夹紧尾巴可能提示害怕。它们都是线索，不是脱离场景就能套用的情绪标签。',
    reasons: '尾巴既参与交流，也帮助平衡；动作含义会随身体其他部分和周围事件变化。盯着玩具时尾尖轻动，不一定与被反复抚摸时大幅甩尾相同。耳朵后压、肌肉紧绷或试图走开，会让停止接近的信号更明确。也不要只凭竖尾就认定猫愿意被抱起或接受所有抚摸。',
    actions: ['同时看耳朵、躯干、眼睛和是否主动靠近，从一段行为而非一瞬间判断。', '抚摸中出现尾巴明显拍打、身体僵硬时先停手，让猫选择下一步。', '给夹尾、退缩的猫留出距离与藏身处，不追着摸，不拉尾巴试探。'],
    keywords: ['尾巴', '竖尾', '甩尾', '夹尾'],
  }, {
    question: 'How should I read an upright, swishing or tucked tail?',
    shortAnswer: 'An upright tail often accompanies a friendly approach; strong swishing can suggest arousal or irritation, and tucking can suggest fear. These are clues, not context-free emotional labels.',
    reasons: 'Tails support balance as well as communication. Meaning changes with posture and events nearby. A twitching tip while watching a toy need not mean the same thing as a tail lashing during prolonged petting. Flattened ears, tense muscles and attempts to leave strengthen the signal to stop approaching. An upright tail does not automatically invite picking up or every kind of touch.',
    actions: ['Read ears, body, eyes and voluntary approach together over a sequence of behavior.', 'Pause petting when the tail starts thumping or the body stiffens, allowing the cat to choose what happens next.', 'Give a tucked-tail, retreating cat space and shelter; do not follow to pet or pull their tail to test a reaction.'],
    keywords: ['tail', 'upright', 'swishing', 'tucked'],
  }, [references.tail, references.body]),
  article('cat-belly-display', 'communication', {
    question: '猫露肚皮是在邀请摸肚子吗？',
    shortAnswer: '露出肚皮可能说明此刻比较放松，但不等于邀请摸腹部。很多猫不喜欢这个敏感部位被碰，尊重它的选择能让互动更舒服。',
    reasons: '猫翻身可能出现在打招呼、休息或玩耍中，单一动作不能替它表达触摸许可。肚皮是脆弱部位，手突然靠近可能引起抓抱或咬手；这不表示猫在骗人。个别猫能接受腹部接触，也需要看当次状态，而不是把以前允许过当作以后都允许。',
    actions: ['可以轻声回应或陪它待着，不必每次露肚皮都伸手。', '需要抚摸时让猫先靠近，试着短暂摸头侧或下巴等它喜欢的位置，然后停下。', '出现抓手、甩尾、耳朵后转或离开时立即停止，不用再次摸肚子来验证反应。'],
    keywords: ['肚皮', '露肚子', '翻身', '抚摸'],
  }, {
    question: 'Is showing the belly an invitation for a belly rub?',
    shortAnswer: 'A belly display can accompany relaxation, but it does not automatically invite abdominal touching. Many cats dislike contact with this sensitive area; respect their choice.',
    reasons: 'Rolling over can occur during greeting, resting or play. One movement cannot provide permission for touch. The belly is vulnerable, and a hand approaching suddenly can trigger grabbing or biting; the cat is not tricking you. Some individuals accept belly contact, but their state at this moment still matters. Previous acceptance does not mean permanent permission.',
    actions: ['Acknowledge them gently or sit nearby without reaching for every exposed belly.', 'Let the cat approach first, briefly touch a preferred area such as the side of the head or chin, then pause.', 'Stop for grabbing, tail lashing, ears turning back or leaving; do not repeat the belly touch to test their response.'],
    keywords: ['belly', 'rolling', 'touch', 'petting'],
  }, [references.belly]),
  article('cat-hissing', 'communication', {
    question: '猫哈气、耳朵后压时，主人应该怎么回应？',
    shortAnswer: '把这些表现当作需要距离的信号，立即减少接近与触碰。先给猫退路，再找诱因；硬抱、训斥或逼它接受互动容易增加恐惧。',
    reasons: '猫在害怕、被堵住或受到刺激时可能用哈气保护自己，疼痛也可能降低触摸耐受。耳朵后压需要与全身状态一起读，不能凭一次哈气给它贴上凶猫标签。常见场景包括陌生人接近、同伴堵路和被持续抚摸。平时温和的猫突然抗拒接近，也需要排除身体不适。',
    actions: ['停手并缓慢拉开距离，让猫能自行退到安全位置，避免堵门或围观。', '暂时移开可识别的刺激，安排藏身点，并告诉家人不要强行抱出。', '待它完全平静且主动靠近后，再用短互动重新建立舒适感，记录容易触发反应的场景。'],
    watch: '新出现、反复发生或与某处触摸有关的防御反应，咨询兽医；排除健康原因后可寻求合格行为专业人员帮助。',
    keywords: ['哈气', '耳朵后压', '害怕', '防御'],
  }, {
    question: 'How should I respond to hissing and flattened ears?',
    shortAnswer: 'Treat these as signals to give distance and stop approaching or touching. Offer an escape route before investigating the trigger; forced holding or scolding can increase fear.',
    reasons: 'A frightened, cornered or overstimulated cat may hiss defensively. Pain can also reduce tolerance of touch. Read ears with the whole body rather than labeling a cat aggressive after one hiss. Common settings include unfamiliar people, another cat blocking access or continued petting. Sudden resistance in a normally comfortable cat also warrants checking for discomfort.',
    actions: ['Stop touching, move away slowly and leave an unobstructed route to safety.', 'Remove an identifiable trigger where possible, offer a hiding place and ask family members not to drag the cat out.', 'Resume brief interaction only after they are calm and approach voluntarily; record recurring triggers.'],
    watch: 'Seek veterinary advice for new, recurrent or touch-specific defensive reactions. A qualified behavior professional can help once medical causes are assessed.',
    keywords: ['hiss', 'flattened ears', 'fear', 'defensive'],
  }, [references.aggression, references.cornellAggression]),
  article('cat-small-meals', 'feeding', {
    question: '猫为什么喜欢少量多次进食？',
    shortAnswer: '分成多次的小餐，可以贴近猫寻找和吃掉小型猎物的行为需求。关键是把合适的全天总量分开，而不是每次走到食盆旁都无限加餐。',
    reasons: '猫的进食安排同时受到习惯、食物形式与环境安全感影响。有的猫愿意分次吃，有的已经适应固定饭点。多猫挤在同一食盆前，也可能让某只猫一次不敢吃够。幼猫、怀孕哺乳期或有疾病的猫需要单独制定方案，不能照搬成年健康猫的频次和总量。',
    actions: ['先与兽医确定适合年龄、体况和健康状态的日粮，再分成几次小餐。', '用称量和剩食记录管理总量，定时喂食器与益智喂食器中的食物也计入日粮。', '为每只猫安排安静、分开的进食点；新喂食器从容易取食的形式开始，不让猫因为不会使用而少吃。'],
    keywords: ['少量多次', '小餐', '喂食', '日粮'],
  }, {
    question: 'Why do cats often prefer small, frequent meals?',
    shortAnswer: 'Several small meals can support the behavioral pattern of finding and eating small prey. Divide an appropriate daily ration rather than endlessly topping up whenever a cat visits the bowl.',
    reasons: 'Habits, food type and feeling safe influence feeding patterns. Some cats graze; others adapt to set meals. Sharing a crowded bowl may prevent one cat from eating enough comfortably. Kittens, pregnant or nursing cats and cats with illness need individual plans rather than the schedule and portions used for a healthy adult.',
    actions: ['Agree a daily ration suited to age, body condition and health with your veterinarian, then divide it into smaller meals.', 'Measure food and leftovers; count food in timed and puzzle feeders within the daily allowance.', 'Provide quiet, separate feeding stations. Start new puzzle feeders at an easy level so learning to use them does not reduce intake.'],
    keywords: ['small meals', 'frequent', 'feeding', 'ration'],
  }, [references.meal, references.nutrition]),
  article('cat-begging-food', 'feeding', {
    question: '猫总讨食，怎么判断是否吃够了？',
    shortAnswer: '讨食不能单独证明饥饿，也不能证明日粮已经够了。结合实际摄入、体重趋势和体况，比凭叫声或空食盆判断更可靠。',
    reasons: '猫可能喜欢食物、互动或已经学会用讨食得到零食；也可能被其他猫抢食，实际吃得比估算少。包装建议针对一般情况，需求还受年龄、活动、绝育和疾病影响。如果胃口明显增加却体重下降，不应只是继续加粮；体重超标也不能突然断食或自行进行激进减重。',
    actions: ['记录主食、零食和家人额外投喂，并在多猫家庭确认每只猫实际吃到的份量。', '定期用同一方式称重，请兽医示范体况评估，再据趋势调整日粮。', '把部分日粮用于容易的觅食游戏，并增加陪玩；让家人遵守统一安排，避免重复喂食。'],
    watch: '新出现的持续饥饿、体重下降或饮水排尿变化，咨询兽医排查；减重方案也应个体化。',
    keywords: ['讨食', '吃够', '体重', '零食'],
  }, {
    question: 'How can I tell whether a cat who begs has eaten enough?',
    shortAnswer: 'Begging alone establishes neither hunger nor adequate intake. Actual consumption, weight trends and body condition provide a better basis than vocal requests or an empty bowl.',
    reasons: 'A cat may enjoy food, seek interaction or have learned that begging earns treats. Another cat may steal food, making intake lower than assumed. Package guides are starting points; age, activity, neutering and illness affect needs. Increased appetite with weight loss should not simply lead to more food. An overweight cat should not be abruptly fasted or put on a drastic diet.',
    actions: ['Record meals, treats and extra feeding by family; confirm what each cat actually eats in a shared household.', 'Weigh consistently and ask a veterinarian to demonstrate body-condition assessment before adjusting the ration.', 'Use some of the daily ration in easy foraging games and offer more play; agree a household schedule to avoid duplicate feeding.'],
    watch: 'Seek veterinary advice for new persistent hunger, weight loss or changes in drinking and urination. Weight-loss plans also need individual guidance.',
    keywords: ['begging', 'hungry', 'weight', 'treats'],
  }, [references.obesity, references.feeding, references.senior]),
  article('cat-drinking-water', 'feeding', {
    question: '猫看起来不爱喝水，可以怎样改善？',
    shortAnswer: '先记得湿粮也提供水分，看见喝水次数少不一定等于缺水。让干净水更容易取得，并尝试不同位置和容器，比强行灌水更合适。',
    reasons: '饮水需求受食物含水量、年龄、环境和健康影响，不能只比较两只猫喝水的次数。水盆靠近猫砂、太吵或被其他猫占据，可能降低使用意愿；不同猫对静水、流动水和容器有自己的偏好。喷泉并非必需品，也不能保证增加饮水或预防泌尿疾病。',
    actions: ['每天更换清水、清洗水盆，设置多个安静且远离猫砂盆的饮水点。', '尝试稳定的宽口容器；想试喷泉时保留普通水盆，并按说明清洁设备。', '可讨论适合的完整湿粮，逐步调整饮食；已有处方饮食或疾病的猫先与兽医确认。'],
    watch: '饮水突然增加或减少、尿量变化或精神食欲变差时咨询兽医；不要用牛奶代替清水。',
    keywords: ['喝水', '饮水', '湿粮', '水盆'],
  }, {
    question: 'How can I encourage a cat who seems reluctant to drink?',
    shortAnswer: 'Wet food supplies water too, so few observed drinking visits do not establish dehydration. Make clean water accessible and try different locations and containers rather than forcing water.',
    reasons: 'Diet moisture, age, environment and health influence requirements. Comparing two cats’ drinking frequency can mislead. A noisy location, litter nearby or another cat guarding a bowl may discourage use. Preferences for still water, running water and containers vary. A fountain is optional and cannot guarantee higher intake or prevent urinary disease.',
    actions: ['Refresh water and clean bowls daily; provide several quiet drinking spots away from litter boxes.', 'Try stable, wide containers. If testing a fountain, keep an ordinary bowl available and clean the device as directed.', 'Discuss a suitable complete wet food and introduce changes gradually; check with your veterinarian before altering a prescription diet or an ill cat’s diet.'],
    watch: 'Consult a veterinarian for sudden drinking changes, altered urine output or reduced energy or appetite. Milk should not replace water.',
    keywords: ['water', 'drinking', 'wet food', 'bowl'],
  }, [references.drinking, references.nutrition]),
  article('cat-resource-placement', 'feeding', {
    question: '食碗、水碗和猫砂盆怎样摆放更合适？',
    shortAnswer: '把进食、饮水和如厕区分开，并放在安静、容易到达的位置。多猫家庭需要分散的资源，不能只增加一排挨在一起的碗。',
    reasons: '猫在吃饭和排泄时需要安全感，不希望被突然打扰或被同伴堵住。食物旁的水不一定是它最愿意使用的水源，靠近猫砂盆也容易受到气味和清洁问题影响。把所有资源集中在同一角落，可能让一只猫守住入口；高处进食点也不适合已经行动困难的猫。',
    actions: ['食碗、水碗、猫砂盆各选不同位置，避开洗衣机、忙碌通道和突然关闭的门。', '多猫分开设置进食和饮水点，必要时用家具遮挡视线，并观察有没有守碗或抢食。', '从猫实际行走路线检查可达性，给幼猫和行动不便的猫保留低处资源，不用跳跃才能吃喝。'],
    keywords: ['摆放', '食碗', '水碗', '资源'],
  }, {
    question: 'Where should food, water and litter boxes go?',
    shortAnswer: 'Separate feeding, drinking and toileting areas in quiet, accessible locations. In multi-cat homes, spread resources out rather than adding a row of bowls in one spot.',
    reasons: 'Cats need to feel safe while eating and toileting, without surprise interruptions or blocked access. Water beside food may not be their preferred source, while litter nearby brings smells and hygiene concerns. Concentrating everything in one corner lets another cat guard the entrance. Elevated feeding is unsuitable for a cat who has difficulty getting there.',
    actions: ['Choose separate places for food, water and litter, away from appliances, busy passages and doors that can close unexpectedly.', 'Give cats separate food and water stations, using visual barriers if useful; watch for guarding or stolen food.', 'Check access along the routes cats actually use. Keep low-level resources for kittens and cats with impaired mobility so eating and drinking do not require jumping.'],
    keywords: ['placement', 'food bowl', 'water bowl', 'resources'],
  }, [references.water, references.meal]),
  article('cat-appetite-change', 'feeding', {
    question: '猫突然挑食、少吃或不吃，该怎么办？',
    shortAnswer: '突然吃得少、换了吃法或完全不吃，应尽快联系兽医。不要把新变化一律当作挑嘴，也不要靠饿它来迫使接受新粮。',
    reasons: '食物气味、环境压力和同伴干扰可以影响进食，但牙口疼痛、恶心或疾病也可能让猫闻一闻就走开。老年猫与幼猫有各自的风险，已有疾病的猫还可能需要调整照护方案。只舔汤汁或吃几颗零食，不表示摄入已经足够；不吃的原因不能从一段描述直接诊断。',
    actions: ['立即记录最后正常进食时间、实际吃下的量以及呕吐、精神和排泄情况，向兽医说明。', '联系医院的同时提供熟悉且适合它的食物、干净餐具与安静空间，不频繁摆满新口味。', '已有处方食物吃不下时向兽医讨论替代方案，不擅自停用照护安排或强行用注射器灌食。'],
    watch: '完全不吃或明显少吃应及时寻求专业指导，不设自行等待一天两天的门槛；幼猫、病猫或伴随虚弱和反复呕吐更需紧急评估。',
    keywords: ['挑食', '不吃', '食欲', '少吃'],
  }, {
    question: 'What should I do if my cat suddenly eats less or stops eating?',
    shortAnswer: 'Contact a veterinarian promptly for reduced intake, altered eating or refusal of food. Do not dismiss a new change as fussiness or use hunger to force acceptance of a new diet.',
    reasons: 'Smell, stress and other animals can affect meals, but dental pain, nausea or illness may also cause a cat to sniff and walk away. Kittens, seniors and cats with existing disease have particular risks. Licking gravy or eating a few treats does not establish sufficient intake. A description alone cannot diagnose the cause.',
    actions: ['Record the last normal meal, the amount actually eaten, vomiting, energy and toileting, and tell the veterinary team.', 'While contacting the clinic, offer familiar suitable food in a clean bowl in a quiet place; avoid constantly presenting many new flavors.', 'Discuss alternatives if a prescribed diet is refused. Do not change the care plan independently or force food by syringe.'],
    watch: 'Seek advice promptly for no food or markedly reduced intake without waiting one or two days. Kittens, ill cats, weakness or repeated vomiting need especially urgent assessment.',
    keywords: ['appetite', 'not eating', 'fussy', 'less food'],
  }, [references.appetite, references.inappetence]),
  article('cat-burying-poop', 'litter', {
    question: '猫为什么会埋便便，有时又不埋？',
    shortAnswer: '扒砂和掩埋是常见如厕行为，但不是每只猫每次都会完成。偶尔不埋不能单独证明它在示威、报复，或是家中的老大。',
    reasons: '猫对猫砂的触感与盆内空间有个体偏好，也会受早期经验影响。有的只是扒盆边，有的离开得很快；盆太小、砂不合意或周围有打扰时，可先检查这些条件。需要关注的是原来稳定的习惯突然改变，是否同时出现便便性状、频率或排便舒适度变化，而不是强迫所有猫学同一种流程。',
    actions: ['提供足够转身和扒砂的空间，用熟悉、无香味且猫愿意使用的猫砂。', '及时铲除排泄物，安排安静、不易被其他动物打扰的如厕位置。', '记录掩埋变化以及便便情况；要比较猫砂时另加试用盆，保留原来的选择，不抓着爪子教它埋。'],
    watch: '突然不埋并伴随排便用力、疼痛、持续腹泻或便便明显变化，咨询兽医先排除健康问题。',
    keywords: ['埋便便', '不埋', '扒砂', '排便'],
  }, {
    question: 'Why does my cat bury poop sometimes but not always?',
    shortAnswer: 'Digging and covering are common toileting behaviors, but not every cat completes them every time. Leaving poop uncovered does not prove defiance, revenge or dominance.',
    reasons: 'Cats have individual substrate and space preferences shaped partly by early experience. Some paw at the rim or leave quickly. A small box, disliked litter or interruptions are useful things to check. Focus on a change from this cat’s established pattern, including stool appearance, frequency and comfort, rather than forcing every cat to follow an identical sequence.',
    actions: ['Offer space to turn and dig, using familiar, unscented litter the cat accepts.', 'Scoop promptly and choose a quiet location where other animals will not interrupt.', 'Record changes and stool quality. Test another litter in an additional box while keeping the familiar choice; do not physically move their paws to teach covering.'],
    watch: 'Seek veterinary advice when a sudden change accompanies straining, pain, persistent diarrhea or markedly altered stool.',
    keywords: ['bury poop', 'uncovered', 'digging', 'stool'],
  }, [references.substrate, references.digestive, references.soiling]),
  article('cat-litter-box-setup', 'litter', {
    question: '猫砂盆的大小、位置和数量怎么安排？',
    shortAnswer: '盆应够大，便于转身和扒砂，摆在安静、可到达且不易被堵路的位置。多猫家庭常以每猫一个、另加一个为起点，再按实际关系和布局调整。',
    reasons: '盆的可用性不只由数量决定：并排放的盆可能仍只有一条入口，紧张的猫无法安全选择。盖子、砂的触感和清洁程度也影响使用意愿。幼猫和行动困难的猫需要容易跨入的入口；楼层多或面积大的家中，不能要求猫长途走到唯一的厕所。盆约为猫鼻尖到尾根长度的一点五倍，可作为选尺寸的参考。',
    actions: ['选能舒展转身的盆，提供低入口选择；有盖盆不合意时可并列尝试开放盆。', '把盆分散到不同位置和需要的楼层，远离食水与噪声，避免容易遭到伏击的死角。', '每天铲砂、定期清洗，按猫的使用情况调整，不因某个盆暂时少用就立刻撤掉。'],
    keywords: ['猫砂盆', '数量', '尺寸', '位置'],
  }, {
    question: 'How large should litter boxes be, and how many do I need?',
    shortAnswer: 'Choose roomy boxes in quiet, accessible places with safe approaches. One per cat plus one extra is a common starting point, adjusted to relationships and the home’s layout.',
    reasons: 'Numbers alone do not ensure access: adjacent boxes may share one guarded route. Covers, litter texture and cleanliness affect preference. Kittens and cats with mobility problems need manageable entrances; large or multi-level homes need convenient locations. About one and a half times the cat’s nose-to-tail-base length is a useful sizing guide.',
    actions: ['Choose space to turn and dig, with a low entrance when needed. Offer an open box alongside a covered one if the cover seems unwelcome.', 'Spread boxes across locations and necessary floors, away from food, water, noise and corners where another cat can block escape.', 'Scoop daily and clean regularly; adjust from observed use rather than immediately removing a less-used box.'],
    keywords: ['litter box', 'number', 'size', 'location'],
  }, [references.litter, references.urinaryGuide]),
  article('cat-litter-box-avoidance', 'litter', {
    question: '猫不肯用猫砂盆，要检查哪些原因？',
    shortAnswer: '先排除健康与疼痛问题，同时检查盆、砂、清洁和通行是否合适。盆外排泄不等于报复主人，惩罚会让问题更难处理。',
    reasons: '排尿或排便不舒服可能与盆外排泄有关，行动困难也可能让入口变得太高。环境方面，换砂、强气味、突然响起的电器或另一只猫守路，都可能影响选择。猫在盆旁排泄说明值得检查使用条件，但不能据此排除疾病。即使看起来是在喷尿，也需要根据完整病史判断。',
    actions: ['联系兽医，记录排泄时间、姿势、位置、尿便变化与最近家庭调整。', '保留熟悉的盆与猫砂，增设大而干净、入口易用的盆，并确保多条安全通路。', '用适合宠物环境的清洁方法去除污迹与气味，避免刺激性气味；不训斥、不把猫按进盆里。'],
    watch: '频繁用力但仅少尿或无尿、排泄时疼痛或叫喊，立即就医；不要只通过换砂尝试解决。',
    keywords: ['不用猫砂盆', '乱尿', '盆外排泄', '厕所'],
  }, {
    question: 'What should I check if my cat avoids the litter box?',
    shortAnswer: 'Assess health and pain first while checking litter, cleanliness and access. Toileting outside the box is not revenge, and punishment can make it harder to resolve.',
    reasons: 'Uncomfortable urination or defecation can be involved, while mobility problems may make an entrance too high. New litter, strong smells, noisy appliances or another cat guarding the route can also affect choice. Toileting beside a box suggests checking the setup, but does not rule out illness. Even apparent spraying needs a complete history.',
    actions: ['Contact a veterinarian and record timing, posture, location, urine or stool changes and recent household changes.', 'Keep familiar litter and boxes, adding a large, clean, accessible box with safe routes.', 'Remove mess and odor with suitable pet-environment cleaning methods; avoid irritating scents, scolding or forcing the cat into the box.'],
    watch: 'Repeated straining with little or no urine, painful toileting or crying requires immediate veterinary care, not just a litter change.',
    keywords: ['litter avoidance', 'house soiling', 'outside box', 'toilet'],
  }, [references.soiling, references.litter]),
  article('cat-urine-spraying', 'litter', {
    question: '喷尿标记和普通排尿有什么区别？',
    shortAnswer: '喷尿常见于站立、尾巴抬起抖动，向垂直表面排出少量尿；普通排尿通常蹲下形成较大尿团。但姿势和位置都不是绝对诊断。',
    reasons: '喷尿是气味交流的一种方式，家中出现新动物、环境变化或资源竞争可能与它有关，公母猫和已绝育猫都可能喷尿。蹲着尿在盆外也可能是排尿问题，而不是标记。尿量、位置和姿态会有例外，因此不能只凭墙上有尿就认定是行为问题，也不能保证绝育后一定消失。',
    actions: ['记录或安全拍下姿势、尿量与位置，观察有没有尿痛、频繁如厕或同伴堵路。', '新出现的喷尿先与兽医讨论，排除医疗原因后再评估资源、陌生气味及猫之间的关系。', '分散食水、厕所和躲藏点，清洁尿迹，减少外来猫等刺激；不惩罚，也不把所有资源集中在一处。'],
    watch: '少尿、血尿或用力排尿需及时就医；用力却尿不出按急症处理，不能当成普通标记。',
    keywords: ['喷尿', '标记', '尿团', '气味'],
  }, {
    question: 'How does urine spraying differ from ordinary urination?',
    shortAnswer: 'Spraying often involves standing with a raised, quivering tail and depositing a small amount on a vertical surface. Ordinary urination usually involves squatting and more urine, but neither pattern is diagnostic.',
    reasons: 'Spraying communicates scent and may accompany new animals, environmental changes or resource competition. Either sex and neutered cats can spray. Squatting outside a box may reflect urinary problems rather than marking. Exceptions exist in amount, posture and location, so urine on a wall does not establish a behavioral cause, and neutering does not guarantee elimination.',
    actions: ['Record posture, amount and location, with video if safely possible; watch for pain, frequent trips or blocked access.', 'Discuss new spraying with a veterinarian, then assess resources, unfamiliar scents and cat relationships after medical evaluation.', 'Spread out resources, clean marks and reduce identifiable triggers such as unfamiliar cats outside; avoid punishment.'],
    watch: 'Reduced urine, blood or straining needs prompt assessment. Straining without producing urine is an emergency, not ordinary marking.',
    keywords: ['spraying', 'marking', 'urination', 'scent'],
  }, [references.spraying, references.urinaryGuide]),
  article('cat-cannot-urinate', 'litter', {
    question: '猫频繁进猫砂盆，却只有少量尿或没有尿怎么办？',
    shortAnswer: '立即联系兽医或急诊医院并带猫就医。反复用力、少尿或尿不出可能涉及尿道阻塞，这是可以迅速危及生命的急症。',
    reasons: '不同泌尿问题的外观表现相似，主人不能仅凭叫声、尿团或公母猫自行判断有没有阻塞。公猫风险较高，但任何猫出现这些迹象都应立即评估。有时排尿用力会被误当成便秘，或少量滴尿被误认为还能正常排尿；不要因此推迟。没有叫喊也不能证明不疼或安全。',
    actions: ['现在就向医院说明反复如厕、用力及少尿或无尿，确认能接诊并尽快出发。', '用稳固航空箱安静运送，随手带上已知病史和排尿记录，不为收集样本或拍照耽误。', '不要挤压腹部、尝试自行通尿、强行灌水或给药；这些不能替代急诊检查和处理。'],
    watch: '即使只有少量尿、猫仍会走动或未呕吐，也不要等待自行好转。若精神衰弱、呕吐或倒下，向急诊明确说明这些情况。',
    keywords: ['尿不出', '少尿', '尿道阻塞', '急诊'],
  }, {
    question: 'What if my cat keeps visiting the litter box but produces little or no urine?',
    shortAnswer: 'Contact a veterinarian or emergency clinic immediately and take your cat for care. Repeated straining with little or no urine may involve urethral obstruction, a rapidly life-threatening emergency.',
    reasons: 'Urinary disorders can look similar; owners cannot rule out obstruction from sounds, clumps or sex. Male cats are at higher risk, but every cat showing these signs needs immediate assessment. Straining may be mistaken for constipation, and a few drops may be mistaken for normal urination. Neither should delay care, and silence does not establish comfort or safety.',
    actions: ['Tell the clinic now about repeated trips, straining and little or no urine; confirm reception and leave promptly.', 'Transport quietly in a secure carrier with available history and records; do not delay for samples or photographs.', 'Do not press the abdomen, attempt to unblock urine, force water or give medicines; these cannot replace emergency assessment and treatment.'],
    watch: 'Do not wait for improvement even if a few drops appear, the cat can walk or has not vomited. Tell emergency staff about weakness, vomiting or collapse.',
    keywords: ['no urine', 'straining', 'obstruction', 'emergency'],
  }, [references.urinary, references.urinaryGuide], true),
  article('cat-scratching-furniture', 'play', {
    question: '猫为什么抓沙发，怎样引导使用抓板？',
    shortAnswer: '抓挠是维护爪子、伸展和留下气味信息的正常行为。目标是提供猫愿意使用的替代位置，让抓挠有合适出口，而不是完全禁止。',
    reasons: '沙发稳定、材质容易抓，位置又在日常路线中，可能比放在角落里摇晃的抓柱更有吸引力。不同猫喜欢竖抓或横抓，已有的抓痕和气味也会引导再次使用。与同伴的紧张可能影响抓挠地点，但不能只凭家具损坏就判定原因。把猫爪按在抓板上示范，可能让它反而避开。',
    actions: ['在已经常抓的地方和睡醒会经过的位置放稳固抓柱或横抓板，给它充分伸展空间。', '试不同方向和材质，主动使用后立即给予它喜欢的奖励，多猫家庭分开放置。', '用安全罩布保护家具，待替代点稳定使用后再逐步移动；不喷水、追打或强行抓着爪子训练。'],
    keywords: ['抓沙发', '抓板', '抓柱', '抓挠'],
  }, {
    question: 'Why does my cat scratch the sofa, and how can I encourage a scratching post?',
    shortAnswer: 'Scratching maintains claws, stretches the body and leaves scent information. Provide an appealing alternative rather than trying to eliminate this normal behavior.',
    reasons: 'A sofa may be stable, easy to grip and conveniently located, unlike a wobbly post hidden in a corner. Cats differ in their preference for vertical or horizontal surfaces, and familiar marks and scent can encourage reuse. Social tension may affect locations, but damage alone cannot identify the cause. Physically placing paws on a post may make it less appealing.',
    actions: ['Put stable posts or pads beside existing scratching areas and places used after waking, with room for a full stretch.', 'Try different orientations and materials, reward voluntary use promptly and spread surfaces out for multiple cats.', 'Protect furniture with safe covers, then move a well-used alternative gradually; avoid spraying, chasing or manipulating paws.'],
    keywords: ['scratching', 'sofa', 'post', 'pad'],
  }, [references.scratch, references.training]),
  article('cat-play-biting', 'play', {
    question: '猫为什么扑脚、咬手，怎样调整互动方式？',
    shortAnswer: '移动的手脚可能被当成游戏目标，年轻猫尤其常见。把追逐需求转向玩具，并在咬人之前安排主动游戏，比事后惩罚更有帮助。',
    reasons: '猫的游戏常包含潜伏、扑击和抓抱，幼年用手逗玩可能让它持续把身体当玩具。游戏不足、突然快速移动也可能诱发扑脚；但咬人并非都由玩耍造成，害怕、过度抚摸或疼痛也需区分。抓咬时猛烈甩手、奔跑或继续逗弄，可能让情境更兴奋，不适合用来测试它是否在玩。',
    actions: ['所有家人改用长杆玩具或可抱咬的玩具，手脚不再参与追逐游戏。', '在容易扑脚的时段提前提供短游戏，留出潜伏和抓住玩具的机会。', '出现抓咬时尽量停止快速动作，安全结束互动并给距离；不要用打、喷水或吓唬来纠正。'],
    watch: '突然咬人、非游戏场景反复攻击或触摸时疼痛，应先请兽医评估，再讨论行为调整。',
    keywords: ['扑脚', '咬手', '游戏', '抓咬'],
  }, {
    question: 'Why does my cat pounce on feet or bite hands during play?',
    shortAnswer: 'Moving hands or feet may become play targets, especially for young cats. Redirect the hunting drive to toys and offer play before biting starts rather than punishing afterward.',
    reasons: 'Play includes stalking, pouncing and grabbing. Hand-based kitten games may teach that bodies are toys. Limited play and sudden movement can also trigger pouncing. Biting is not always play: fear, unwanted petting or pain require a different assessment. Jerking hands, running or continuing to tease can intensify arousal rather than clarify intent.',
    actions: ['Have everyone use long-handled or suitable kick toys instead of hands and feet for chase games.', 'Offer short games before predictable pouncing periods, with opportunities to stalk and capture a toy.', 'Minimize rapid movement during grabbing, end contact safely and give space; do not hit, spray or frighten the cat.'],
    watch: 'Seek veterinary assessment for sudden biting, repeated attacks outside play or painful reactions to touch before planning behavior work.',
    keywords: ['pouncing', 'biting hands', 'play', 'feet'],
  }, [references.bite, references.cornellAggression]),
  article('cat-wand-play', 'play', {
    question: '逗猫棒怎样玩，才符合猫的捕猎习惯？',
    shortAnswer: '让玩具像小猎物一样移动，给猫观察、潜伏、追逐和抓住的机会。一直在脸前挥舞，或每次都让它扑空，不一定是舒服的玩法。',
    reasons: '有的猫喜欢沿地面逃走的目标，有的更关注轻快的空中动作，偏好会随体力和环境变化。蹲着盯玩具也可能在准备行动，不能把每个停顿都当作没兴趣。幼猫容易兴奋，老年猫可能喜欢较低、较慢的动作；游戏不需要大量跳高才算成功，也不应强迫追到疲惫。',
    actions: ['在安全、地面防滑的区域移动玩具，模拟远离猫的逃跑路线，并穿插停顿与遮挡。', '定期让它真正抓住玩具，松开拉力，避免突然猛拽正在咬住的目标。', '分成短时段，按猫的呼吸与参与意愿停止；结束后收好线绳玩具，别留下无人看管的悬挂线。'],
    keywords: ['逗猫棒', '捕猎', '追逐', '游戏方式'],
  }, {
    question: 'How can wand play support my cat’s hunting behavior?',
    shortAnswer: 'Move the toy like prey and allow watching, stalking, chasing and capture. Waving constantly in the cat’s face or preventing every catch may not provide satisfying play.',
    reasons: 'Some cats prefer targets moving along the ground; others notice light airborne movement. Preferences depend on fitness and setting. Watching while crouched may be preparation rather than disinterest. Kittens can become highly excited, while seniors may prefer low, slow movements. Play need not involve high jumps or continue until exhaustion.',
    actions: ['Use a safe area with good footing, move the toy away like escaping prey and include pauses and hiding.', 'Allow genuine catches regularly, release tension and avoid jerking a toy from the cat’s mouth.', 'Use short sessions and stop according to breathing and willingness to participate; store string toys safely afterward rather than leaving hanging cords unattended.'],
    keywords: ['wand', 'hunting', 'chase', 'play technique'],
  }, [references.play]),
  article('cat-toy-interest', 'play', {
    question: '猫对玩具没兴趣，怎样调整玩法？',
    shortAnswer: '先改变时段、运动方式和难度，观察它喜欢哪一种。站着看、缓慢跟随也可以是参与；不需要购买更多玩具或强迫跑跳来证明活动够了。',
    reasons: '玩具始终摊在地上可能失去新鲜感，突然靠近脸部或过快的动作也可能让猫退开。有些猫在人多、另一只猫围观时不愿玩，适合单独互动。老年猫和行动不便的猫可能需要低处目标。若原来爱玩却突然完全不参加，先考虑身体或环境变化，而不是直接说它懒。',
    actions: ['选择猫自然清醒的时间，轮换少量玩具，试地面滑动、短暂停住或从遮挡后出现。', '为多猫家庭分别安排游戏，避免让胆小的猫在竞争中退到一边。', '用容易成功的低强度玩法开始，给观察和休息时间；益智取食中的食物计入日粮。'],
    watch: '参与度突然下降，或伴随跳跃犹豫、身体僵硬与食欲变化，应请兽医检查。',
    keywords: ['玩具', '没兴趣', '不爱玩', '丰富环境'],
  }, {
    question: 'How can I adapt play if my cat seems uninterested in toys?',
    shortAnswer: 'Try changing timing, movement and difficulty, then observe preferences. Watching or following slowly can be participation; more purchases or forced running are not required.',
    reasons: 'A toy left out continuously may become less novel. Fast movements or toys pushed toward the face may discourage approach. Some cats avoid play with people or other cats nearby and prefer individual sessions. Seniors and cats with mobility limits may need low targets. A sudden loss of previously enjoyed play calls for checking health and environment rather than labeling laziness.',
    actions: ['Play when the cat is naturally awake, rotate a few toys and try ground movement, pauses or appearing from behind cover.', 'Play individually in multi-cat homes so a timid cat does not lose opportunities through competition.', 'Start with easy, low-intensity games and allow watching and rest; count puzzle food within the daily ration.'],
    watch: 'Ask a veterinarian about sudden withdrawal from play, hesitant jumping, stiffness or appetite changes.',
    keywords: ['toys', 'uninterested', 'enrichment', 'less play'],
  }, [references.indoor, references.chronicPain]),
  article('cat-toy-safety', 'play', {
    question: '绳线、羽毛和激光玩具有哪些使用注意事项？',
    shortAnswer: '线绳和容易脱落的部件需要监督，游戏后收起。优先选能抓住的实体玩具；激光不能完成真实捕获，也不应照向眼睛。',
    reasons: '线、橡皮筋和小零件可能被吞下或造成缠绕，玩具标为宠物用品也不能代替日常检查。激光玩耍与追光、盯影等重复行为在问卷研究中有相关性，但并未证明必然因果。不能因为加了零食就宣称风险已被消除，也不应把每只追光的猫都诊断成强迫行为。',
    actions: ['每次检查玩具接合处和磨损，破损或会被吞食的玩具立即收走；线绳只在有人监督时使用。', '以实体捕猎游戏为主；若使用激光，避免眼睛与反光面，并转向可抓住的玩具结束。', '发现持续搜寻光点或难以停止时停用激光，记录情况并咨询兽医或行为专业人员。'],
    watch: '怀疑吞线或玩具部件时立即联系兽医；口中或肛门露出的线不要自行拉扯。',
    keywords: ['绳线', '羽毛', '激光', '玩具安全'],
  }, {
    question: 'What precautions apply to string, feather and laser toys?',
    shortAnswer: 'Supervise cords and detachable parts, then put them away. Favor physical toys that can be caught; a laser cannot provide a real capture and must not be aimed at eyes.',
    reasons: 'String, elastic bands and small parts may be swallowed or cause entanglement; a pet-product label does not replace inspection. Survey research links laser play with repetitive light-related behavior but does not establish inevitable causation. Adding a treat has not been shown to remove risk, and chasing light alone is not a diagnosis of compulsive behavior.',
    actions: ['Inspect connections and wear each time, remove damaged or swallowable toys and use cords only under supervision.', 'Prioritize physical hunting games. If using a laser, avoid eyes and reflective surfaces and switch to a catchable toy to finish.', 'Stop laser use for persistent searching or difficulty disengaging; record behavior and seek professional advice.'],
    watch: 'Contact a veterinarian immediately for suspected swallowed string or parts. Do not pull string protruding from the mouth or anus.',
    keywords: ['string', 'feather', 'laser', 'toy safety'],
  }, [references.safe, references.laser, references.foreignBodies, references.swallowedString]),
  article('cat-normal-grooming', 'grooming', {
    question: '猫为什么经常舔毛？',
    shortAnswer: '舔毛是猫日常清洁和整理被毛的重要方式，也可能出现在放松或情境变化之后。需要看皮肤和整体状态，不能只凭舔了多久认定有问题。',
    reasons: '舌头和舔舐动作帮助移除松毛、污物并整理毛发。不同猫的习惯和毛量不同，主人也可能只看到其中一段。短暂舔舐不必阻止，但持续集中舔同一处、出现秃斑或皮肤损伤，就超出了普通清洁的范围。老年猫可能因为动作困难而不易照顾背部和后躯，毛发变乱同样值得关注。',
    actions: ['在日常互动中看看被毛是否整齐、有无红斑或打结，观察相较平常是否明显改变。', '按毛长提供轻柔梳理帮助，清掉容易吞下的松毛，不把所有舔毛都打断。', '保持可预测的生活与安静休息区，记录异常舔舐集中在哪些部位，而不是先假定一定焦虑。'],
    watch: '突然舔得更多或更少、舔出伤口或明显脱毛，联系兽医查原因。',
    keywords: ['舔毛', '清洁', '被毛', '梳理'],
  }, {
    question: 'Why does my cat groom so often?',
    shortAnswer: 'Licking is an important part of cleaning and maintaining the coat. It may also occur around relaxed moments or changes in a situation; duration alone does not establish a problem.',
    reasons: 'The tongue and licking movements remove loose hair and debris and organize the coat. Habits and coat density differ, and owners see only parts of a day. Brief grooming need not be interrupted. Persistent focus on one area, bald patches or damaged skin go beyond routine cleaning. Older cats may struggle to reach the back and hindquarters, so a deteriorating coat matters too.',
    actions: ['During ordinary interaction, check coat condition, redness and mats and compare with the usual pattern.', 'Offer gentle coat-appropriate brushing to remove loose hair without interrupting every grooming episode.', 'Keep daily routines predictable and resting areas quiet; record the location of unusual licking rather than assuming anxiety.'],
    watch: 'Seek veterinary advice for a sudden increase or decrease, wounds or obvious hair loss.',
    keywords: ['grooming', 'licking', 'coat', 'cleaning'],
  }, [references.groom, references.licking]),
  article('cat-overgrooming', 'grooming', {
    question: '猫舔到掉毛、皮肤发红，应该怎么办？',
    shortAnswer: '预约兽医检查，已经舔出秃斑、红肿或伤口不能只当作爱干净。改善环境可以同时进行，但不要未经检查就把原因归为压力。',
    reasons: '瘙痒、寄生虫、过敏、疼痛和皮肤问题都可能引起过度舔舐，某些情境也可能与压力有关。不同原因的外观常有重叠，没看见跳蚤也不能排除相关问题；把患处简单遮住并不等于处理了诱因。反复舔破皮肤可能使情况恶化，病史与检查比根据秃斑位置自行诊断更可靠。',
    actions: ['记录开始时间、部位、皮肤照片及近期食物、清洁用品或家庭变化，带给兽医。', '保持安静和熟悉的资源安排，减少同伴竞争，但不要让环境调整拖延检查。', '避免自行涂人用药膏、精油或更换多种产品；是否需要防舔措施及后续处理由兽医指导。'],
    watch: '皮肤破损、渗液、明显疼痛或迅速加重时尽快就医；治疗后仍反复舔，应复诊讨论而非自行加药。',
    keywords: ['过度舔毛', '掉毛', '红斑', '秃斑'],
  }, {
    question: 'What should I do if licking causes hair loss or red skin?',
    shortAnswer: 'Arrange veterinary assessment: bald, inflamed or wounded skin is not ordinary cleanliness. Environmental improvements can proceed alongside assessment without assuming stress is the cause.',
    reasons: 'Itch, parasites, allergies, pain and skin disorders can drive excessive licking; stress may also be involved. Their appearance overlaps, and not seeing fleas does not rule them out. Covering an area alone does not address its cause. Repeated licking can worsen damage, so history and examination are more reliable than self-diagnosis from the location of a bald patch.',
    actions: ['Record onset, affected areas, photographs and recent food, cleaning-product or household changes for the veterinarian.', 'Maintain quiet, familiar resources and reduce competition, without letting environmental changes postpone assessment.', 'Avoid human creams, essential oils or trying many products. Ask the veterinarian whether protection from licking and further treatment are needed.'],
    watch: 'Seek prompt care for open skin, discharge, significant pain or rapid worsening. Persistent licking after treatment warrants reassessment, not independent extra medication.',
    keywords: ['overgrooming', 'hair loss', 'red skin', 'bald patches'],
  }, [references.licking, references.skin]),
  article('cat-bathing', 'grooming', {
    question: '猫需要经常洗澡吗？',
    shortAnswer: '大多数能正常自我梳理的有毛猫不需要常规洗澡。是否洗澡应取决于实际污染、皮肤状况和个体需求，而不是套用人的清洁频率。',
    reasons: '强行洗澡可能带来压力，也会影响皮肤和毛发的自然状态。少量普通污物有时用温水湿布局部清洁即可，毛打结则主要需要梳理或专业处理。无毛猫或某些皮肤病患者可能有不同方案，应由兽医个体化指导。被毛沾上可能有毒的物质不能等它自己舔干净，也不是直接套用日常洗澡步骤的情况。',
    actions: ['先检查是否只是小范围污渍，能安全处理时轻柔局部清洁，不为固定日历强行洗。', '确有洗澡需要时先询问兽医，使用适合猫的用品，减少限制和噪声，并做好保暖。', '疑似有毒物质沾身时防止继续舔舐并立即联系兽医，说明物质名称，按专业指导处理。'],
    keywords: ['洗澡', '清洁', '无毛猫', '污物'],
  }, {
    question: 'Does my cat need regular baths?',
    shortAnswer: 'Most coated cats who groom normally do not need routine baths. Base bathing on contamination, skin health and individual needs rather than a human hygiene schedule.',
    reasons: 'Forced bathing can be stressful and affect the coat’s natural condition. A small amount of ordinary dirt may only need gentle local cleaning with a warm damp cloth. Mats need grooming or professional attention rather than a bath alone. Hairless cats and some skin conditions may need a different veterinarian-guided plan. Potentially toxic contamination should never be left for the cat to lick clean or handled as an ordinary bath.',
    actions: ['Check whether a small patch can be cleaned gently and safely instead of imposing calendar-based baths.', 'Ask the veterinarian when bathing is needed, use suitable cat products, minimize restraint and noise and keep the cat warm.', 'Prevent licking suspected toxic contamination and contact a veterinarian immediately with the substance details for instructions.'],
    keywords: ['bathing', 'bath', 'hairless', 'cleaning'],
  }, [references.bath, references.safe, references.toxicHazards]),
  article('cat-brushing-routine', 'grooming', {
    question: '短毛猫和长毛猫怎样安排梳毛？',
    shortAnswer: '短毛猫可从每周轻柔梳理开始，长毛猫通常需要每日检查和梳理。频率还要看换毛、打结和猫自身能否有效清洁，不能只看品种名称。',
    reasons: '长毛更容易纠结，腋下和身体活动处尤其需要关注；短毛猫在换毛期或行动变差时也可能需要更多帮助。老年、肥胖或刚接受治疗的猫可能不容易够到某些位置。梳理是观察皮肤与被毛的机会，但不应为了完成全身而持续拉扯。已经贴近皮肤的紧结可能让猫疼痛，不适合剪刀直接剪。',
    actions: ['根据毛长和偏好选柔软刷子或合适梳子，顺毛方向轻柔处理，先从能接受的部位开始。', '长毛分成短时段检查，短毛按松毛量调整；每次观察皮肤和猫的放松程度。', '遇到紧结、皮肤看不清或一碰就痛，停止拉扯，先由兽医检查并安排安全处理。'],
    keywords: ['梳毛', '长毛', '短毛', '打结'],
  }, {
    question: 'How should I plan brushing for short-haired and long-haired cats?',
    shortAnswer: 'Weekly gentle brushing is a starting point for short coats; long coats usually need daily checking and grooming. Adjust for shedding, mats and the cat’s ability to groom, not breed alone.',
    reasons: 'Long fur tangles more readily, particularly around moving areas such as the armpits. Short-coated cats may also need help during shedding or reduced mobility. Seniors, overweight cats and cats recovering from treatment may struggle to reach areas. Grooming offers a chance to inspect the skin, but completing the whole coat should not require pulling. Tight mats near skin may hurt and should not be cut with scissors.',
    actions: ['Choose a soft brush or appropriate comb suited to coat and preference; work gently with the coat from tolerated areas.', 'Split long-coat care into short sessions and adjust short-coat care to loose hair, checking skin and comfort each time.', 'Stop at tight mats, hidden skin or painful reactions; have a veterinarian assess them first and arrange safe treatment.'],
    keywords: ['brushing', 'long-haired', 'short-haired', 'mats'],
  }, [references.longhair, references.chronicPain]),
  article('cat-cooperative-care', 'grooming', {
    question: '猫抗拒梳毛、剪指甲，怎样逐步适应？',
    shortAnswer: '把护理拆成猫愿意参与的小步骤，及时奖励，并在它还放松时结束。新出现的抗拒先检查疼痛，不用固定压住来完成训练。',
    reasons: '工具声音、碰爪和过去不舒服的经历都可能影响接受程度。认识刷子、接受一两下梳理和完成全身，是不同阶段；剪爪也可以分次完成。幼猫适合建立温和经验，成年猫同样能循序学习，但进度没有统一期限。爪内有血管神经，实际剪的位置和是否需要修剪应先请专业人员示范。',
    actions: ['猫健康且放松时，先让它看工具、嗅工具并获得奖励，再逐步短暂接触。', '每次只推进一小步，例如摸爪后放开，或梳两下就停；紧绷、退缩时退回更容易的步骤。', '学会辨认爪内粉红区域，仅在能安全操作时剪尖端；不会判断或猫很害怕时请兽医团队协助。'],
    watch: '一碰某处就疼、爪子嵌入肉垫或有皮肤损伤时先就医；训练不能替代必要的医疗处理。',
    keywords: ['剪指甲', '护理训练', '抗拒', '梳毛'],
  }, {
    question: 'How can I help a cat accept brushing and nail care?',
    shortAnswer: 'Break care into small voluntary steps, reward promptly and finish while the cat is comfortable. Assess new resistance for pain instead of using restraint as training.',
    reasons: 'Tool sounds, paw contact and previous uncomfortable experiences influence acceptance. Seeing a brush, tolerating a couple of strokes and completing the coat are separate stages; claw care can also be split up. Gentle experience helps kittens, and adults can learn gradually too, without a fixed deadline. Claws contain nerves and blood vessels, so ask a professional to demonstrate whether and where trimming is needed.',
    actions: ['Practice when healthy and relaxed: reward looking at or sniffing equipment before brief contact.', 'Advance one small step at a time, such as touching and releasing a paw or brushing twice. Return to an easier step for tension or withdrawal.', 'Learn to identify the pink quick and trim only the tip when safe; ask the veterinary team if uncertain or the cat is fearful.'],
    watch: 'Pain on touching, a claw growing into a pad or damaged skin needs veterinary care before training.',
    keywords: ['nail trimming', 'cooperative care', 'brushing', 'training'],
  }, [references.training, references.claws, references.vcaPain]),
  article('cat-boxes-hiding', 'environment', {
    question: '猫为什么喜欢纸箱和躲藏？',
    shortAnswer: '遮挡和边界可以提供安全的休息、观察或游戏空间。喜欢躲进纸箱很常见，重要的是安全进出，而不是把躲藏一律解释成胆小或不亲人。',
    reasons: '有的猫在箱子里睡觉，有的把它作为潜伏和扑玩具的起点。能暂时避开家人或其他动物，也让它更容易选择何时互动。喜欢箱子不意味着任何包装都适合：胶带、订书钉、提绳和残留物都可能带来风险。躲藏若比平常明显增加，要把环境压力和身体不适都纳入考虑。',
    actions: ['提供干净稳固的箱子或半遮挡窝，去除钉子、绳线与松散胶带，保持通风且能自由出去。', '把藏身处放在安静位置，多猫分开设置；有人来访也不强行把猫抱出来展示。', '留意猫是否仍正常出来进食、排泄和活动，收拾纸箱或移动家具前先确认它的位置。'],
    watch: '躲藏突然增加，伴随进食减少、动作变化或疼痛表现，联系兽医排查。',
    keywords: ['纸箱', '躲藏', '安全感', '藏身处'],
  }, {
    question: 'Why do cats like boxes and hiding places?',
    shortAnswer: 'Sheltered boundaries can offer secure rest, observation and play. Enjoying a box is common; safe access matters more than interpreting all hiding as shyness or lack of affection.',
    reasons: 'Some cats sleep in boxes; others use them to stalk toys. A retreat from people or other animals gives control over when to interact. Not all packaging is suitable: staples, cords, loose tape and residues can create hazards. A clear increase in hiding deserves consideration of both environmental stress and discomfort.',
    actions: ['Offer a clean, stable box or sheltered bed without staples, cords or loose tape, with ventilation and a free exit.', 'Place retreats quietly and separately for multiple cats; do not pull a cat out to show visitors.', 'Check that normal eating, toileting and activity continue, and locate the cat before moving furniture or discarding boxes.'],
    watch: 'Seek veterinary advice for increased hiding with reduced food, altered movement or signs of pain.',
    keywords: ['boxes', 'hiding', 'safe place', 'shelter'],
  }, [references.boxes, references.hiding, references.vcaPain]),
  article('cat-new-home-hiding', 'environment', {
    question: '新到家的猫一直躲着，怎样帮助它适应？',
    shortAnswer: '先提供安静、可控制的小范围生活区，让猫决定何时出来。新环境中的躲藏很常见，但仍要确认它能正常吃喝和排泄，不能只等它自己适应。',
    reasons: '气味、声音、路线和人都变了，即使在原来住所很自信的猫，也可能暂时谨慎。适应速度取决于个体经历，没有统一的出躲藏期限。反复伸手、拖出或围观可能增加压力；不敢出来与生病也可能同时发生，所以关注摄入和排泄比每天要求亲近更重要。',
    actions: ['在安全房间分开放置食物、水和猫砂盆，准备藏身处与熟悉气味的垫子，检查门窗。', '安静陪伴并保持日常安排，减少访客和强行抚摸，允许它自己靠近和探索。', '记录实际进食与排泄，放松后逐渐开放更多空间；遇到其他宠物时仍按分步介绍进行。'],
    watch: '不吃、明显少吃或持续精神差，应及时联系兽医；反复用力排尿却很少或没有尿，应立即就医，不把这些当作必须忍过的适应期。',
    keywords: ['新到家', '适应', '躲着', '安全房间'],
  }, {
    question: 'How can I help a newly arrived cat who keeps hiding?',
    shortAnswer: 'Offer a quiet, manageable starting area and let the cat choose when to emerge. Hiding is common after a move, but confirm normal intake and toileting rather than merely waiting.',
    reasons: 'Smells, sounds, routes and people have changed. Even a previously confident cat may be cautious. Experience influences the pace, with no universal deadline for leaving a hide. Reaching in, dragging out or gathering around may increase pressure. Fear and illness can occur together, so intake and toileting are more useful measures than demanding closeness each day.',
    actions: ['Set up separate food, water and litter in a secure room, with retreats and familiar bedding; check doors and windows.', 'Keep routines steady and sit quietly nearby, limiting visitors and forced petting while allowing voluntary approach.', 'Record intake and toileting, expand space gradually as the cat relaxes and introduce other pets in stages.'],
    watch: 'Contact a veterinarian promptly for food refusal, markedly reduced intake or persistent low energy. Repeated straining with little or no urine needs immediate veterinary care; these are not an adaptation period to endure.',
    keywords: ['new home', 'settling', 'hiding', 'safe room'],
  }, [references.newhome, references.shy, references.inappetence, references.urinary]),
  article('cat-household-changes', 'environment', {
    question: '搬家、来客或装修时，怎样减少猫的压力？',
    shortAnswer: '提前准备能安静休息、保持熟悉气味且不会被误开门的安全区。把变化拆小，保留日常节奏，让猫可以避开不愿参与的场景。',
    reasons: '噪声、陌生人、门窗频繁开合和气味改变，都会使熟悉环境变得难以预测。老年猫可能更难适应，多猫在狭小暂住区也可能增加竞争。没有明显哈气并不代表完全放松，进食、藏身和活动变化同样需要观察。装修中还要考虑粉尘、涂料和逃逸等实际危险，单靠安抚无法替代空间隔离。',
    actions: ['提前布置远离施工或人流的房间，分开食水和厕所，带上熟悉床垫并让猫先认识这里。', '提醒家人、访客或工人关门，必要时设置门口提示；搬运时用可靠航空箱。', '保持喂食与陪伴时间，允许自由躲藏；不能安全隔离施工时安排合适的临时住所。'],
    watch: '变化中出现新发生或明显的食欲下降、异常排泄或明显退缩，应联系兽医，同时检查环境安全。',
    keywords: ['搬家', '来客', '装修', '压力'],
  }, {
    question: 'How can I reduce stress during a move, visits or building work?',
    shortAnswer: 'Prepare a quiet retreat with familiar smells and protection from accidentally opened doors. Introduce manageable changes, keep routines and allow withdrawal from unwanted activity.',
    reasons: 'Noise, unfamiliar people, frequent door opening and altered smells make a home less predictable. Seniors may find changes harder, while cramped temporary space can increase competition. Absence of hissing does not establish comfort; eating, hiding and activity matter too. Dust, coatings and escape are practical construction hazards that reassurance alone cannot resolve.',
    actions: ['Prepare a room away from work and traffic, with separate resources and familiar bedding, and introduce it before the event.', 'Ask family, visitors and workers to keep doors secure, using a reminder if helpful; use a reliable carrier for transport.', 'Keep feeding and companionship predictable and permit hiding; arrange suitable temporary accommodation if the work cannot be safely separated.'],
    watch: 'Seek veterinary advice for a new or marked decrease in appetite, unusual toileting or marked withdrawal while checking environmental safety.',
    keywords: ['moving', 'visitors', 'building work', 'stress'],
  }, [references.moving, references.stress, references.senior]),
  article('cat-indoor-enrichment', 'environment', {
    question: '室内猫需要哪些休息、攀爬和探索空间？',
    shortAnswer: '室内生活需要同时满足安全休息、分散资源、捕猎游戏与自主探索。空间的可用性和选择比单纯买很多玩具更重要，要按每只猫的能力安排。',
    reasons: '猫需要能避开干扰的地方，也需要观察、抓挠和探索的机会。高处和遮挡可增加选择，但所有资源集中在一棵猫树上，未必适合多猫。熟悉气味和可预测的人猫互动也是环境的一部分。幼猫应防止缝隙和跌落，行动不便的猫则需要台阶、低处替代点和容易到达的食水。',
    actions: ['设置安静的睡窝、藏身处与牢固攀爬平台，确保退出路线，并按行动能力提供台阶。', '分散食物、水、厕所和抓挠点，让不同猫不必挤在同一入口或互相争抢。', '轮换可安全探索的物件，安排短游戏和容易的觅食活动；窗边观察点配可靠防护，避免坠落。'],
    keywords: ['室内猫', '环境丰富', '攀爬', '探索'],
  }, {
    question: 'What resting, climbing and exploration spaces does an indoor cat need?',
    shortAnswer: 'Support secure rest, distributed resources, hunting-style play and voluntary exploration. Useful choices matter more than buying many toys, and access should match each cat’s abilities.',
    reasons: 'Cats need retreats from interruption and opportunities to watch, scratch and investigate. Height and shelter add options, but placing everything on one tree may fail in a multi-cat home. Familiar scents and predictable interactions are also part of the environment. Protect kittens from gaps and falls, and offer steps, low alternatives and easy resource access for cats with mobility difficulties.',
    actions: ['Provide quiet beds, retreats and secure climbing platforms with exit routes and suitable steps.', 'Spread food, water, litter and scratching points so cats need not compete at one entrance.', 'Rotate safe things to investigate and offer brief games and easy foraging. Secure window-side observation spots against falls.'],
    keywords: ['indoor cat', 'enrichment', 'climbing', 'exploration'],
  }, [references.indoorNeeds, references.pillars, references.indoor]),
  article('cat-carrier-training', 'environment', {
    question: '猫不愿进航空箱，怎样进行日常适应训练？',
    shortAnswer: '把航空箱长期作为家中可自由进出的休息点，从主动靠近开始奖励。训练应在平静、健康时进行，不等出门那天才追着抓猫。',
    reasons: '只在看病前拿出箱子，容易让它预告陌生经历；箱门声音、被关住和晃动也可能各自需要适应。看箱子、进入、短暂关门和移动，是不同步骤，不宜一次完成。有的猫进步快，有的需要更多时间，不能用相同天数判断成功。能安心躺在箱里，比被塞进去后不出声更能说明训练效果。',
    actions: ['选稳固、容易开启与清洁的箱子，固定好门，放熟悉垫子并留在平常生活区。', '从靠近、探头到走进去逐步奖励，食物放在它能轻松取得的位置，不突然关门。', '自在进入后再短暂关门、立即打开，逐步尝试抬起和短途移动；退缩时减小难度。'],
    watch: '急需就医时不能等待训练完成；联系医院讨论当次安全入箱和运输办法。',
    keywords: ['航空箱', '猫包', '入箱', '训练'],
  }, {
    question: 'How can I train my cat to feel comfortable in a carrier?',
    shortAnswer: 'Make the carrier a familiar, freely accessible resting spot and reward voluntary approaches. Practice while calm and healthy rather than chasing a cat on departure day.',
    reasons: 'A carrier appearing only before clinic visits can predict unfamiliar experiences. Doors, confinement and movement may each require practice. Looking, entering, briefly closing and carrying are separate steps, not one session. Progress varies, so success should not be measured by a fixed number of days. Relaxed resting inside is more informative than silence after being pushed in.',
    actions: ['Use a secure, easy-access, washable carrier with the door held safely open and familiar bedding in the living area.', 'Reward approaching, looking inside and entering; make food easy to reach and avoid surprise door-closing.', 'Once comfortable, close briefly and reopen, then build up gentle lifting and short movement; reduce difficulty when the cat withdraws.'],
    watch: 'Do not delay urgent veterinary care until training is complete. Ask the clinic about safe loading and transport for that visit.',
    keywords: ['carrier', 'travel', 'entering', 'training'],
  }, [references.carrier, references.kitten]),
  article('cat-kneading', 'relationships', {
    question: '猫为什么踩奶？',
    shortAnswer: '踩奶起源于幼猫吃奶时的动作，有些猫成年后仍会保留。常在舒适情境中看到，但成年猫为何持续这样做并没有一个能解释所有个体的确定答案。',
    reasons: '猫可能在软毯、睡窝或人的腿上交替按爪，有时伴随呼噜。保留早期动作和舒适感是常见解释，但不能因此断言它把主人当妈妈、一定很爱主人，或曾经太早断奶。没有踩奶也不代表关系不好。需要区分普通按爪与同时咬下、吞入布料的情况，后者不是可以放心忽略的小习惯。',
    actions: ['如果猫放松且没有损伤，让它使用干净、结实、没有松线的垫子。', '爪尖让人不舒服时加一层毯子或轻轻换位置，不惩罚、不抓着爪子制止。', '观察它是否只是在按压，避免留下容易被咬碎吞下的布料，给猫自主离开的空间。'],
    keywords: ['踩奶', '按爪', '软毯', '亲近'],
  }, {
    question: 'Why does my cat knead?',
    shortAnswer: 'Kneading begins during nursing in kittens, and some retain it into adulthood. It often occurs in comfortable settings, but no single confirmed explanation covers every adult cat.',
    reasons: 'A cat may alternate paws on a blanket, bed or lap, sometimes while purring. Retained early behavior and comfort are common explanations, but do not prove that the cat sees a person as their mother, always feels affection or was weaned too early. Absence of kneading does not indicate a poor relationship. Ordinary pawing should be distinguished from biting off and swallowing fabric.',
    actions: ['If relaxed and causing no damage, allow a clean, sturdy resting pad without loose threads.', 'Use a blanket or gently change position if claws hurt, without punishment or grabbing paws.', 'Check whether the cat is merely pressing and remove fabrics they might chew apart or swallow, while allowing them to leave freely.'],
    keywords: ['kneading', 'making biscuits', 'blanket', 'bond'],
  }, [references.knead]),
  article('cat-affiliative-signals', 'relationships', {
    question: '猫蹭人、顶头或慢慢眨眼，可能表达什么？',
    shortAnswer: '这些行为常见于熟悉、放松的互动，也可能涉及气味交流或寻求关注。可以温和回应，但不要把一个动作当作必然爱意或同意被抱起的证明。',
    reasons: '脸部蹭物和蹭人会留下熟悉气味，主动顶头可出现在靠近互动时。慢眨眼在放松的人猫交流中很常见，具体含义仍需要结合姿态与场景。有些猫亲近却不喜欢被抱，另一些更喜欢待在附近，不能按表达形式给关系打分。猫有没有机会自主靠近和离开，是观察舒服程度的重要线索。',
    actions: ['保持柔和姿态，可轻轻慢眨眼后把目光移开，避免持续直视逼近。', '让猫先选择靠近，尝试它喜欢的头侧或下巴短抚摸，然后停下看是否继续邀请。', '它转身、退开或休息时就留空间；把每天可预测的短互动当作建立关系的基础。'],
    keywords: ['蹭人', '顶头', '慢眨眼', '关系'],
  }, {
    question: 'What might rubbing, head-bumping or slow blinking mean?',
    shortAnswer: 'These behaviors often occur in familiar, relaxed interactions and may involve scent exchange or attention. Respond gently without treating one movement as proof of affection or permission to pick up.',
    reasons: 'Facial rubbing leaves familiar scent, and voluntary head-bumping may accompany approach. Slow blinking is common in relaxed human–cat interaction, with meaning still dependent on posture and setting. Some sociable cats dislike being held; others prefer nearby company. Their style of expression is not a relationship score. Freedom to approach and leave is an important comfort clue.',
    actions: ['Use a relaxed posture, try a gentle slow blink and look aside rather than approaching with a fixed stare.', 'Let the cat approach, briefly touch a preferred cheek or chin area, then pause for their choice.', 'Give space when they turn away, retreat or rest, and build the relationship through predictable brief interactions.'],
    keywords: ['rubbing', 'head bump', 'slow blink', 'bond'],
  }, [references.blink, references.environment, references.body]),
  article('cat-petting-boundaries', 'relationships', {
    question: '猫被摸着摸着突然咬人，怎样识别停止信号？',
    shortAnswer: '抚摸可能超过当次耐受，咬之前常有较细的变化。采用短抚摸加停顿，让猫选择是否继续；突然改变的耐受也需要排除疼痛。',
    reasons: '甩尾、耳朵转向后方、身体绷紧、转头看手或试图离开，都可能提示该结束了。不是每只猫都会按固定顺序表现，也不能要求它先给明显警告才允许停。猫喜欢靠近不等于喜欢持续抚摸全身，睡着时或敏感部位的接触也可能不同；平时能接受的地方突然不能碰要格外留意。',
    actions: ['从猫主动靠近开始，短暂摸它偏好的部位，停手看它是否再次蹭来。', '第一次出现紧绷或转头等信号就停，保留离开路线，不抓住它继续摸。', '记下容易引起反应的位置和时长，家人采用一致方式，不惩罚咬人也不重复触摸测试。'],
    watch: '耐受突然下降、固定部位一碰就咬或伴随动作变化，预约兽医检查。',
    keywords: ['摸着咬人', '停止信号', '抚摸', '边界'],
  }, {
    question: 'How can I recognize when my cat wants petting to stop?',
    shortAnswer: 'Petting may exceed tolerance in that moment, with subtle changes before a bite. Use brief contact and pauses so the cat can choose; a sudden loss of tolerance also warrants checking for pain.',
    reasons: 'Tail lashing, ears turning back, tension, looking toward the hand or attempting to leave can signal a stopping point. Not every cat shows these in a fixed order or gives an obvious warning. Enjoying proximity is not the same as wanting continuous full-body strokes. Touch during sleep or on sensitive areas may differ, and new resistance in a previously tolerated spot deserves attention.',
    actions: ['Start with voluntary approach, briefly stroke a preferred area and pause to see whether they rub toward you again.', 'Stop at the first tension or head turn, leaving a route away instead of holding them for more contact.', 'Note sensitive areas and duration, agree a consistent family approach and avoid punishment or repeated testing.'],
    watch: 'Arrange veterinary assessment for sudden reduced tolerance, biting at a particular touched area or altered movement.',
    keywords: ['petting', 'biting', 'stop signals', 'boundaries'],
  }, [references.aggression, references.vcaPain]),
  article('cat-introductions', 'relationships', {
    question: '家里迎来第二只猫，怎样逐步介绍彼此？',
    shortAnswer: '从各自安全生活区开始，逐步交换气味、隔着可靠屏障见面，再尝试短暂接触。根据双方放松程度推进，没有必须在几天内成为朋友的目标。',
    reasons: '猫对同伴的接受差异很大，增加一只猫不一定让原来的猫更快乐。直接关在一起容易让第一次经验充满压力；即使没有打架，盯视、堵路和一方躲藏也可能是紧张。幼猫可能活动需求更高，老年猫更需要不被追逐的休息时间，安排应考虑双方而不是只照顾新来的猫。',
    actions: ['先分开设置完整资源，确认新猫的健康与预防照护，并让原来的猫保留日常区域。', '双方平静时交换带气味物件，再通过不能钻过的屏障进行短接触，保留远离的选择。', '放松后逐步短暂同处，配合各自喜欢的活动；紧绷、堵路或追赶时退回前一步并拉开距离。'],
    watch: '拒食或进食明显减少时及时咨询兽医；持续躲藏或冲突时寻求兽医及合格行为专业人员帮助，不让它们靠打架自行解决。',
    keywords: ['第二只猫', '介绍', '新猫', '多猫'],
  }, {
    question: 'How should I introduce a second cat?',
    shortAnswer: 'Begin with separate secure areas, then progress through scent exchange, reliable barriers and brief shared contact. Advance with both cats’ comfort rather than a deadline to become friends.',
    reasons: 'Acceptance varies; adding a cat does not necessarily improve the resident cat’s wellbeing. Immediate confinement together can create stressful first experiences. Staring, blocking and one cat hiding may indicate tension even without fights. Kittens may need more activity while seniors need rest without pursuit, so consider both individuals rather than only the newcomer.',
    actions: ['Provide complete separate resources, confirm the newcomer’s health and preventive care and preserve the resident’s routine area.', 'When both are calm, exchange scented items, then hold short sessions through an escape-proof barrier with freedom to move away.', 'Build brief shared time gradually with preferred activities. Return to an earlier stage and more distance for tension, blocking or pursuit.'],
    watch: 'Seek prompt veterinary advice for food refusal or a marked reduction in intake. Persistent hiding or conflict warrants veterinary and qualified behavior support; do not let cats fight it out.',
    keywords: ['second cat', 'introductions', 'new cat', 'multi-cat'],
  }, [references.introduce, references.tension, references.inappetence]),
  article('cat-play-or-conflict', 'relationships', {
    question: '两只猫是在玩耍还是冲突，主人何时介入？',
    shortAnswer: '看互动是否互有来往、有停顿，并且双方都能退出。持续单向追逐、叫喊、僵硬或堵路，更需要介入；不能只凭没有打伤就说相处很好。',
    reasons: '游戏常较安静，角色会交换，结束后双方容易恢复；但没有一项特征能单独判定。冲突可以很隐蔽，例如一只守在厕所入口、另一只减少走动，未必天天打架。有人把全部追逐都当作玩耍，可能漏掉一直被追的猫。要关注两只的选择、恢复情况和日常资源使用。',
    actions: ['观察完整过程，记录谁追谁、是否能自由离开，以及结束后是否仍躲藏或紧张。', '出现升级时从安全距离用屏障隔开视线，给各自空间冷静；不把手伸进打斗中，也不抱住兴奋的猫。', '检查并分散食水、厕所和休息点，增加绕行路线；反复紧张时寻求专业帮助，必要时重新逐步介绍。'],
    watch: '受伤、突发性格或食欲改变需兽医检查；持续冲突应制定个体化方案，不靠吓唬或强迫同处。',
    keywords: ['打架', '玩耍', '冲突', '多猫关系'],
  }, {
    question: 'Are my cats playing or fighting, and when should I intervene?',
    shortAnswer: 'Look for reciprocity, breaks and freedom for both to leave. Sustained one-way pursuit, vocal distress, stiffness or blocking warrants intervention; lack of injury does not establish harmony.',
    reasons: 'Play is often quieter, includes role changes and allows a relaxed recovery, but no single feature is decisive. Conflict can be subtle: guarding a litter-box approach or another cat moving less may occur without daily fights. Calling every chase play may overlook the cat always being pursued. Consider both cats’ choices, recovery and everyday resource access.',
    actions: ['Watch the whole sequence and record who pursues, whether both can leave and any later hiding or tension.', 'If it escalates, interrupt visual contact with a barrier from a safe distance and give separate space. Keep hands out of fights and do not pick up aroused cats.', 'Distribute resources and alternative routes; seek professional help for repeated tension and use gradual reintroductions if needed.'],
    watch: 'Injury or sudden personality or appetite changes needs veterinary assessment. Ongoing conflict requires an individual plan, without frightening cats or forcing proximity.',
    keywords: ['fighting', 'play', 'conflict', 'cat relationships'],
  }, [references.fighting, references.tension, references.cornellAggression]),
];
